import static enums.Month.*;

import animals.Animal;

import static enums.Mood.*;
import static etc.FondOfWelberg.*;
import animals.Mouse;
import enums.ResultsOfBoardOfDirectors;
import etc.FondOfWelberg;
import etc.ScientificWork;
import people.*;
import places.Cabinet;
import places.Cage;
import places.Lab;
import places.Labyrinth;
import records.Date;

public class Main {
    public static void main(String[] args) {
        Date date = new Date(12, JULY);
        date.print();
        Cage cage = new Cage("клетка");
        Animal mouse = new Mouse("Элджернон", cage);
        mouse.getPlace();
        Cabinet cabinet = new Cabinet("кабинет");
        Person nemur = new Person("Немур", cabinet);
        Person strauss = new Person("Штраус", cabinet);
        Person bart = new Person("Барт", cabinet);
        Person randomPerson1 = new Person(cabinet);
        Person randomPerson2 = new Person(cabinet);
        nemur.getPlace();
        strauss.getPlace();
        bart.getPlace();
        randomPerson1.getPlace();
        randomPerson2.getPlace();
        nemur.setWaitingTime(5);
        strauss.setWaitingTime(5);
        bart.setWaitingTime(5);
        randomPerson1.setWaitingTime(5);
        randomPerson2.setWaitingTime(5);
        Person charly = new Person("Чарли", cabinet);
        charly.getPlace();
        charly.walk();
        charly.notice();
        nemur.pretend(FRIENDLY);
        strauss.pretend(FRIENDLY);
        bart.pretend(FRIENDLY);
        randomPerson1.pretend(FRIENDLY);
        randomPerson2.pretend(FRIENDLY);
        bart.take(mouse);
        charly.handshake(charly,nemur);
        nemur.setMood(DISSATISFIED);
        charly.handshake(charly,strauss);
        charly.walk();
        charly.handshake(charly,bart);
        charly.walk();
        charly.handshake(charly,randomPerson1);
        charly.walk();
        charly.handshake(charly,randomPerson2);
        charly.walk();
        FondOfWelberg fondOfWelberg = new FondOfWelberg();
        fondOfWelberg.getAnAppealFrom(charly);
        ScientificWork scientificWork = new ScientificWork();
        scientificWork.isItMine(charly);
        nemur.reportTo(scientificWork);
        scientificWork.setTime(3);
        scientificWork.enoughTime();
        scientificWork.setTime(15);
        FondOfWelberg.BoardOfDirectors boardOfDirectors = new FondOfWelberg.BoardOfDirectors();
        boardOfDirectors.setResult(ResultsOfBoardOfDirectors.APPROVED);
        boardOfDirectors.getResult();
        nemur.handshake(nemur,charly);
        nemur.setMood(SAD);
        nemur.getMood();
        nemur.pretend(FRIENDLY);
        charly.setScienceExperience(0);
        scientificWork.isItMine(nemur);
        scientificWork.setTime(3);
        scientificWork.setSuccess(scientificWork.enoughTime());
        charly.walk();
        nemur.walk();
        bart.walk();
        Lab lab = new Lab();
        cabinet.deletePeople(charly, bart, nemur);
        cabinet.getPeople();
        charly.setPlace(lab);
        nemur.setPlace(lab);
        bart.setPlace(lab);
        Labyrinth labyrinth = new Labyrinth("Лабиринт №1", 100);
        mouse.setPlace(labyrinth);
        bart.letItGo(mouse, labyrinth);
    }
}